### ISSUE TITLE
Add support for new waste types

### ISSUE THREAD

**Issue by martinbjorgan** [jonkristian/wasteplan_trv#12]
TRV has rolled out 2 new bins (waste types) Glass/Metal and Food waste. Would be nice to have those available as well :)

Great job on the integration! Comes in very handy when you've had shirmps and don't want to toss them in the bin too early 😆

**Comment by jonkristian** [comment]
Thanks :smile: 

I was working on a new version that would easily pick up these changes in wastetypes, but it seems that TRV has changed something in their API so I no longer have access. I see there's an API v2 now, hopefully we can get access so that this component could utilize that, I've sent them an email asking about this, all we can do for now is wait for a response.

**Comment by jonkristian** [comment]
Fixed in v2.0.0
