### ISSUE TITLE
Container combinations missing

### ISSUE THREAD

**Issue by repvik** [jonkristian/wasteplan_trv#5]
I'm trying to use this schedule: https://trv.no/plan/1909/
But I only get sensors that match that of the schedule in #4. Containers can have different schedules, depending on the needs of the housing association. Here, restavfall is picked up every week, paper every other week, and plastics every four weeks. 
Can support for this be added?

**Comment by jonkristian** [comment]
Hello.
~~Not entirely sure what you mean~~, what is the ID of the bin_number you're using?

Also I just realized that the readme is missing some information regarding containers. For container id you need to search it up through [this address](https://trv.no/wp-json/wasteplan/v1/containers/?s=). So instead of `bins` in the url you need to type `containers`.

~~Could that be related to your issue, wrong bin_number?~~

I see the issue, will implement a fix ASAP.

**Comment by repvik** [comment]
The bin_number is correct ({"name":"\u00d8vre Flat\u00e5sveg 45, Kolstadhaugen B\/L","type":"CONTAINERS","plan":null,"calendar":null,"deviations":null,"plans_by_year":null,"id":1909})

But when I use 1909, I get two sensors. sensor.papir_restavfall (which is a valid combination) and sensor.plastemballasje_restavfall
(which is not. If you look at TRV you can see that there are no weeks in which plast+rest is picked up. 
For 1909, valid combinations is rest, rest+papir, rest+papir+plast. 

Edit: See you've already responded

**Comment by jonkristian** [comment]
Yeah. 

This API is a little unusual, because it actually merge results if they are "combined" so to speak. So it could give us a lot of different variations :shrug:

Had this discussion over at #4 where we talked about possibly splitting up and giving you one sensor for each actual waste type. 

I'm not sure how I should approach this, but I will find a solution that works regardless of combinations.

**Comment by repvik** [comment]
If possible, I'd prefer a separate sensor for each type instead of the combined ones. Not sure how well that would work with your code however.

**Comment by jonkristian** [comment]
I will try to make it work :)

**Comment by jonkristian** [comment]
@repvik Please test the latest code in master branch and let me know if this fixes things. Also note that the configuration has changed slightly so make sure to update that as well.

**Comment by repvik** [comment]
Now I got a bunch of sensors. But only restavfall seems to actually work:

`
<html>
<body>


sensor.papirPapir | Ikke bestemt | attribution: Data provided by https://trv.no next_pickup_week: null description: null date_week_start: null date_week_end: null friendly_name: Papir icon: mdi:file
-- | -- | --
sensor.plastemballasjePlastemballasje | Ikke bestemt | attribution: Data provided by https://trv.no next_pickup_week: null description: null date_week_start: null date_week_end: null friendly_name: Plastemballasje icon: mdi:bottle-soda


</body>
</html>
`

**Comment by jonkristian** [comment]
Those sensors looks whack, are you actually seeing `sensor.papirPapir` ?
Also, there's a missing attribute which I added called `pickup_this_week` which I can't see, maybe cache issue?

It works for me with id: 1909, did you correct the config, do you see anything in the logs?

```
sensor:
- platform: wasteplan_trv
  id: 1909
```

**Comment by repvik** [comment]
I didn't notice you had changed bin_number to id, but if I change to id in config, I get invalid config. I'm running master:
Invalid config for [sensor.wasteplan_trv]: [id] is an invalid option for [sensor.wasteplan_trv]. Check: sensor.wasteplan_trv->id. (See ?, line ?).

**Comment by repvik** [comment]
Reinstalled from master twice, now I got correct sensors.

**Comment by jonkristian** [comment]
Great, I will close for now, feel free to report back if any issues.
